// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/shared/components/Hello.fixture';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://192.168.100.86:5002",
  "rendererUrl": null
};

const fixtures = {
  'components/Hello.fixture.tsx': { module: fixture0 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
